# Generated by Django 6.1 on 2026-08-19 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('featured', 'Featured'), ('top_search', 'Top of Search'), ('urgent', 'Urgent'), ('homepage', 'Homepage Featured')], max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='ListingPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('plan_credit', 'Plan credit'), ('admin', 'Admin')], default='purchase', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='listings.listing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='promotions.promotionproduct')),
            ],
            options={
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['listing', 'starts_at', 'ends_at'], name='promotions__listing_2f4d4d_idx'), models.Index(fields=['product', 'starts_at', 'ends_at'], name='promotions__product_730eae_idx')],
            },
        ),
    ]
