# Generated by Django 6.1 on 2026-08-19 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        ("promotions", "0001_initial"),
        ("sellers", "0001_initial"),
        ("subscriptions", "0002_sellersubscription_promotion_credits_remaining"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("card", "Credit card"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(default="BRL", editable=False, max_length=3),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("idempotency_key", models.CharField(max_length=80, unique=True)),
                ("provider", models.CharField(default="mock", max_length=40)),
                (
                    "provider_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("provider_status", models.CharField(blank=True, max_length=80)),
                (
                    "provider_status_detail",
                    models.CharField(blank=True, max_length=120),
                ),
                ("checkout_data", models.JSONField(blank=True, default=dict)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("failure_message", models.TextField(blank=True)),
                ("billing_cycle", models.CharField(blank=True, max_length=12)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="listings.listing",
                    ),
                ),
                (
                    "listing_promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="promotions.listingpromotion",
                    ),
                ),
                (
                    "promotion_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="promotions.promotionproduct",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sellers.sellerprofile",
                    ),
                ),
                (
                    "seller_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="subscriptions.sellerplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.sellersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="payments_pa_status_343680_idx",
                    ),
                    models.Index(
                        fields=["purpose", "status"],
                        name="payments_pa_purpose_8579eb_idx",
                    ),
                    models.Index(
                        fields=["seller", "created_at"],
                        name="payments_pa_seller__7ebf02_idx",
                    ),
                ],
            },
        ),
    ]
