# Generated by Django 6.1 on 2026-08-25.

import marketlift.markets.defaults
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("payments", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="country_code",
            field=models.CharField(db_index=True, default="BR", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="country_code",
            field=models.CharField(
                db_index=True,
                default=marketlift.markets.defaults.default_market_country_code,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default=marketlift.markets.defaults.default_market_currency,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("mobile_money", "Mobile money"),
                    ("bank_transfer", "Bank transfer"),
                    ("ussd", "USSD"),
                    ("eft", "EFT"),
                    ("pix", "Pix"),
                    ("boleto", "Boleto"),
                ],
                max_length=16,
            ),
        ),
    ]
