# Generated by Django 6.1 on 2026-08-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingmedia",
            name="upload",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_media",
                to="uploads.uploadasset",
            ),
        ),
        migrations.AlterField(
            model_name="listingmedia",
            name="url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
