# Generated by Django 6.1 on 2026-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="seller_delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="seller_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
