# Generated by Django 6.1 on 2026-08-25 07:12

import marketlift.markets.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_backfill_brazil_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=marketlift.markets.defaults.default_market_country_code,
                max_length=2,
            ),
        ),
    ]
