import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sellers", "0001_initial"),
        ("listings", "0011_listing_condition_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerPaymentAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="pagarme", max_length=32)),
                ("provider_recipient_id", models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ("status", models.CharField(choices=[("not_started", "Not started"), ("pending", "Pending"), ("active", "Active"), ("restricted", "Restricted"), ("rejected", "Rejected")], db_index=True, default="not_started", max_length=20)),
                ("payout_method", models.CharField(blank=True, choices=[("pix", "Pix"), ("bank_account", "Bank account")], max_length=20)),
                ("payout_destination_masked", models.CharField(blank=True, max_length=160)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("kyc_url", models.URLField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("seller", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payment_account", to="sellers.sellerprofile")),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(db_index=True, max_length=40, unique=True)),
                ("status", models.CharField(choices=[("pending_payment", "Pending payment"), ("paid", "Paid"), ("awaiting_seller", "Awaiting seller"), ("processing", "Processing"), ("shipped", "Shipped"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("refund_pending", "Refund pending"), ("refunded", "Refunded"), ("disputed", "Disputed")], db_index=True, default="pending_payment", max_length=24)),
                ("fulfillment_method", models.CharField(choices=[("shipping", "Shipping"), ("local_delivery", "Local delivery"), ("pickup", "Pickup")], max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_cents", models.PositiveBigIntegerField()),
                ("subtotal_cents", models.PositiveBigIntegerField()),
                ("shipping_amount_cents", models.PositiveBigIntegerField(default=0)),
                ("total_cents", models.PositiveBigIntegerField()),
                ("marketplace_fee_cents", models.PositiveBigIntegerField(default=0)),
                ("seller_proceeds_cents", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("listing_snapshot", models.JSONField(default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commerce_orders", to=settings.AUTH_USER_MODEL)),
                ("listing", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commerce_orders", to="listings.listing")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commerce_orders", to="sellers.sellerprofile")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="CommercePayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="pagarme", max_length=32)),
                ("method", models.CharField(choices=[("pix", "Pix"), ("card", "Card")], max_length=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("refunded", "Refunded"), ("partially_refunded", "Partially refunded"), ("chargeback", "Chargeback")], db_index=True, default="pending", max_length=24)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("provider_order_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("provider_charge_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("provider_transaction_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("checkout_data", models.JSONField(blank=True, default=dict)),
                ("provider_status", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="commerce.order")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("held", "Held"), ("available", "Available"), ("payout_requested", "Payout requested"), ("paid", "Paid"), ("blocked", "Blocked")], db_index=True, default="pending", max_length=24)),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("release_after", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("provider_transfer_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("payout_requested_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="settlement", to="commerce.order")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlements", to="sellers.sellerprofile")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("order_payment", "Order payment"), ("marketplace_fee", "Marketplace fee"), ("seller_receivable", "Seller receivable"), ("refund", "Refund"), ("seller_payout", "Seller payout")], max_length=24)),
                ("amount_cents", models.BigIntegerField()),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="commerce.order")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="sellers.sellerprofile")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("carrier", models.CharField(blank=True, max_length=80)),
                ("tracking_code", models.CharField(blank=True, db_index=True, max_length=160)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("ready", "Ready"), ("shipped", "Shipped"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("failed", "Failed")], db_index=True, default="pending", max_length=24)),
                ("delivery_pin_hash", models.CharField(blank=True, max_length=128)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("proof", models.JSONField(blank=True, default=dict)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="shipment", to="commerce.order")),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved_buyer", "Resolved for buyer"), ("resolved_seller", "Resolved for seller"), ("closed", "Closed")], db_index=True, default="open", max_length=24)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("opened_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commerce_disputes", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="disputes", to="commerce.order")),
            ],
        ),
        migrations.CreateModel(
            name="ProviderWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="pagarme", max_length=32)),
                ("provider_event_id", models.CharField(max_length=160)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("payload_hash", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["buyer", "-created_at"], name="commerce_ord_buyer_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["seller", "status", "-created_at"], name="commerce_ord_seller_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["listing", "status"], name="commerce_ord_listing_idx")),
        migrations.AddIndex(model_name="settlement", index=models.Index(fields=["seller", "status", "release_after"], name="commerce_set_release_idx")),
        migrations.AddIndex(model_name="ledgerentry", index=models.Index(fields=["seller", "kind", "created_at"], name="commerce_led_seller_idx")),
        migrations.AddConstraint(model_name="providerwebhookevent", constraint=models.UniqueConstraint(fields=("provider", "provider_event_id"), name="commerce_unique_provider_event")),
    ]
