# Generated by Django 6.1 on 2026-08-25.

import marketlift.markets.defaults
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sellers", "0004_sellerfollow")]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="country_code",
            field=models.CharField(db_index=True, default="BR", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="country_code",
            field=models.CharField(
                db_index=True,
                default=marketlift.markets.defaults.default_market_country_code,
                max_length=2,
            ),
        ),
    ]
