# Generated by Django 6.1 on 2026-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auth_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_admin", "Super admin"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("support", "Support"),
                    ("finance", "Finance"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
