# Generated by Django 6.1 on 2026-08-25.
# Existing rows belong to the original Brazil deployment; the runtime model
# default becomes market-aware only after those rows are backfilled safely.

import marketlift.markets.defaults
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_admininvitation_adminloginchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(db_index=True, default="BR", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                db_index=True,
                default=marketlift.markets.defaults.default_market_country_code,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="accountsettings",
            name="currency",
            field=models.CharField(
                default=marketlift.markets.defaults.default_market_currency,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="accountsettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("en-GH", "English (Ghana)"),
                    ("en-NG", "English (Nigeria)"),
                    ("en-KE", "English (Kenya)"),
                    ("en-ZA", "English (South Africa)"),
                    ("pt-BR", "Português (Brasil)"),
                    ("fr-CI", "Français (Côte d’Ivoire)"),
                ],
                default=marketlift.markets.defaults.default_market_locale,
                max_length=8,
            ),
        ),
    ]
