# Generated by Django 6.1 on 2026-08-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="messaging.message",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("listing", "Listing"),
                    ("seller", "Seller"),
                    ("user", "User"),
                    ("message", "Message"),
                ],
                max_length=16,
            ),
        ),
    ]
