# Generated by Django 6.1 on 2026-08-25 07:12

import marketlift.markets.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categoryfield_allow_custom_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="pricing_label",
            field=models.CharField(
                default=marketlift.markets.defaults.default_pricing_label,
                max_length=120,
            ),
        ),
    ]
