# Generated by Django 6.1 on 2026-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellersubscription",
            name="promotion_credits_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
