# Generated by Django 6.1 on 2026-08-25 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

MARKETS = {
    "BR": dict(
        country_name="Brazil",
        locale="pt-BR",
        django_language_code="pt-br",
        currency="BRL",
        currency_symbol="R$",
        timezone="America/Sao_Paulo",
        geocoder_language="pt-BR,en",
        payment_provider="mercado_pago",
        payment_methods=["pix", "card", "boleto"],
        identity_label="CPF",
        identity_key="cpf",
        currency_aliases=["r$", "brl", "real", "reais"],
        hierarchical_location_catalog=True,
    ),
    "GH": dict(
        country_name="Ghana",
        locale="en-GH",
        django_language_code="en-gb",
        currency="GHS",
        currency_symbol="GH₵",
        timezone="Africa/Accra",
        geocoder_language="en-GH,en",
        payment_provider="paystack",
        payment_methods=["card", "mobile_money"],
        identity_label="Ghana Card",
        identity_key="national_id",
        currency_aliases=["gh₵", "ghs", "cedi", "cedis", "₵"],
        hierarchical_location_catalog=False,
    ),
    "NG": dict(
        country_name="Nigeria",
        locale="en-NG",
        django_language_code="en-gb",
        currency="NGN",
        currency_symbol="₦",
        timezone="Africa/Lagos",
        geocoder_language="en-NG,en",
        payment_provider="paystack",
        payment_methods=["card", "bank_transfer", "ussd"],
        identity_label="National Identity Number (NIN)",
        identity_key="national_id",
        currency_aliases=["₦", "ngn", "naira"],
        hierarchical_location_catalog=False,
    ),
    "KE": dict(
        country_name="Kenya",
        locale="en-KE",
        django_language_code="en-gb",
        currency="KES",
        currency_symbol="KSh",
        timezone="Africa/Nairobi",
        geocoder_language="en-KE,sw,en",
        payment_provider="paystack",
        payment_methods=["card", "mobile_money"],
        identity_label="National ID",
        identity_key="national_id",
        currency_aliases=["ksh", "kes", "shilling", "shillings"],
        hierarchical_location_catalog=False,
    ),
    "ZA": dict(
        country_name="South Africa",
        locale="en-ZA",
        django_language_code="en-gb",
        currency="ZAR",
        currency_symbol="R",
        timezone="Africa/Johannesburg",
        geocoder_language="en-ZA,en",
        payment_provider="paystack",
        payment_methods=["card", "eft"],
        identity_label="South African ID",
        identity_key="national_id",
        currency_aliases=["zar", "rand"],
        hierarchical_location_catalog=False,
    ),
    "CI": dict(
        country_name="Côte d’Ivoire",
        locale="fr-CI",
        django_language_code="fr",
        currency="XOF",
        currency_symbol="FCFA",
        timezone="Africa/Abidjan",
        geocoder_language="fr-CI,fr,en",
        payment_provider="paystack",
        payment_methods=["card", "mobile_money"],
        identity_label="National ID",
        identity_key="national_id",
        currency_aliases=["xof", "fcfa", "cfa"],
        hierarchical_location_catalog=False,
    ),
}


def seed_market_catalog(apps, schema_editor):
    Market = apps.get_model("platform_settings", "Market")
    SellerPlanMarketPrice = apps.get_model("platform_settings", "SellerPlanMarketPrice")
    PromotionProductMarketPrice = apps.get_model(
        "platform_settings", "PromotionProductMarketPrice"
    )
    SellerPlan = apps.get_model("subscriptions", "SellerPlan")
    PromotionProduct = apps.get_model("promotions", "PromotionProduct")

    bootstrap = str(getattr(settings, "MARKETLIFT_MARKET_CODE", "BR") or "BR").upper()
    if bootstrap not in MARKETS:
        bootstrap = "BR"
    selected = None
    for index, (code, values) in enumerate(MARKETS.items()):
        defaults = dict(values)
        defaults.update(
            identity_provider="disabled",
            currency_subunit_factor=100,
            is_enabled=(code == bootstrap),
            is_default=(code == bootstrap),
            sort_order=index,
        )
        row, _ = Market.objects.update_or_create(code=code, defaults=defaults)
        if code == bootstrap:
            selected = row

    if selected is None:
        return
    # Existing single-market numeric prices are preserved only for the bootstrap
    # market. Other countries require explicit admin pricing, preventing an R$79
    # plan from silently becoming GH₵79 or ₦79.
    for plan in SellerPlan.objects.all():
        SellerPlanMarketPrice.objects.get_or_create(
            market=selected,
            plan=plan,
            defaults={
                "monthly_price": plan.monthly_price,
                "yearly_price": plan.yearly_price,
                "active": plan.active,
            },
        )
    for product in PromotionProduct.objects.all():
        PromotionProductMarketPrice.objects.get_or_create(
            market=selected,
            product=product,
            defaults={"price": product.price, "active": product.active},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0002_marketplace_admin_controls"),
        ("promotions", "0002_expiry_notification"),
        ("subscriptions", "0002_sellersubscription_promotion_credits_remaining"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=2, unique=True)),
                ("country_name", models.CharField(max_length=100)),
                ("locale", models.CharField(max_length=20)),
                ("django_language_code", models.CharField(max_length=20)),
                ("currency", models.CharField(max_length=3)),
                ("currency_symbol", models.CharField(max_length=12)),
                ("timezone", models.CharField(max_length=64)),
                ("geocoder_language", models.CharField(blank=True, max_length=80)),
                (
                    "payment_provider",
                    models.CharField(default="disabled", max_length=40),
                ),
                ("payment_methods", models.JSONField(blank=True, default=list)),
                (
                    "identity_provider",
                    models.CharField(default="disabled", max_length=40),
                ),
                ("identity_label", models.CharField(max_length=100)),
                ("identity_key", models.CharField(max_length=40)),
                ("currency_aliases", models.JSONField(blank=True, default=list)),
                ("currency_subunit_factor", models.PositiveIntegerField(default=100)),
                ("hierarchical_location_catalog", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "country_name"),
            },
        ),
        migrations.CreateModel(
            name="PromotionProductMarketPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("active", models.BooleanField(default=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_prices",
                        to="platform_settings.market",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="promotions.promotionproduct",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "market__sort_order",
                    "product__sort_order",
                    "product__name",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "product"),
                        name="platform_settings_unique_promotion_market_price",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerPlanMarketPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "yearly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_plan_prices",
                        to="platform_settings.market",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="subscriptions.sellerplan",
                    ),
                ),
            ],
            options={
                "ordering": ("market__sort_order", "plan__sort_order", "plan__name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "plan"),
                        name="platform_settings_unique_plan_market_price",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_market_catalog, noop_reverse),
    ]
