# Generated by Django 6.1 on 2026-08-19 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("review", "Under review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("cpf_digest", models.CharField(db_index=True, max_length=64)),
                ("cpf_masked", models.CharField(max_length=14)),
                ("legal_name", models.CharField(max_length=160)),
                ("birth_date", models.DateField()),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national_id", "National ID"),
                            ("drivers_licence", "Driver's licence"),
                            ("passport", "Passport"),
                        ],
                        max_length=24,
                    ),
                ),
                ("document_front_url", models.URLField(blank=True)),
                ("document_back_url", models.URLField(blank=True)),
                ("selfie_url", models.URLField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=80)),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("provider_result", models.TextField(blank=True)),
                ("automated_checks", models.JSONField(blank=True, default=dict)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_submissions",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="verificatio_status_2d6f0e_idx",
                    ),
                    models.Index(
                        fields=["seller", "status"],
                        name="verificatio_seller__0a4c02_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "status"],
                        name="verificatio_risk_le_a6820d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("pending", "review"))),
                        fields=("seller",),
                        name="verifications_one_open_per_seller",
                    )
                ],
            },
        ),
    ]
