# Generated by Django 6.1 on 2026-08-25.

from django.db import migrations, models


def backfill_brazil_identity(apps, schema_editor):
    VerificationSubmission = apps.get_model("verifications", "VerificationSubmission")
    VerificationSubmission.objects.exclude(cpf_digest="").update(
        identity_country_code="BR",
        identity_type="cpf",
        identity_digest=models.F("cpf_digest"),
        identity_masked=models.F("cpf_masked"),
    )


class Migration(migrations.Migration):
    dependencies = [("verifications", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="verificationsubmission",
            name="identity_country_code",
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name="verificationsubmission",
            name="identity_digest",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="verificationsubmission",
            name="identity_masked",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="verificationsubmission",
            name="identity_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="verificationsubmission",
            name="cpf_digest",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="verificationsubmission",
            name="cpf_masked",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.RunPython(backfill_brazil_identity, migrations.RunPython.noop),
    ]
