# Generated by Django 6.1 on 2026-08-19 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("listing_image", "Listing image"),
                            ("message_image", "Message image"),
                            ("verification_document", "Verification document"),
                            ("verification_selfie", "Verification selfie"),
                            ("report_evidence", "Report evidence"),
                            ("avatar", "Avatar"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("ready", "Ready"),
                            ("attached", "Attached"),
                            ("deleted", "Deleted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="prepared",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("storage_alias", models.CharField(default="default", max_length=64)),
                ("object_key", models.CharField(max_length=500, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("expected_size", models.PositiveBigIntegerField()),
                ("actual_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("attached_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["owner", "status", "-created_at"],
                        name="uploads_upl_owner_i_30a395_idx",
                    ),
                    models.Index(
                        fields=["purpose", "status", "expires_at"],
                        name="uploads_upl_purpose_7faa1c_idx",
                    ),
                ],
            },
        ),
    ]
