# Generated by Django 6.1 on 2026-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_processing_variants_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadasset",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("listing_image", "Listing image"),
                    ("message_image", "Message image"),
                    ("verification_document", "Verification document"),
                    ("verification_selfie", "Verification selfie"),
                    ("report_evidence", "Report evidence"),
                    ("avatar", "Avatar"),
                    ("category_image", "Category image"),
                    ("support_attachment", "Support attachment"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
